"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var index_1 = require("./index");
console.log("\u516D\u89AA");
var result = index_1.SIX_RELATIVE.antiVersal(index_1.SIX_REL[0], 1);
console.log(index_1.SIX_REL[0].getSymbol() + "剋" + result.getSymbol());
var result1 = index_1.SIX_RELATIVE.transversal(index_1.SIX_REL[0], 1);
console.log(index_1.SIX_REL[0].getSymbol() + "生" + result1.getSymbol());
console.log("\u4E94\u884C");
var result2 = index_1.FIVE_ELM.antiVersal(index_1.FIVE_EL[0], 1);
console.log(index_1.FIVE_EL[0].getSymbol() + "剋" + result2.getSymbol());
var result3 = index_1.FIVE_ELM.transversal(index_1.FIVE_EL[0], 1);
console.log(index_1.FIVE_EL[0].getSymbol() + "生" + result3.getSymbol());
