"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var index_1 = require("./index");
console.log("\u516D\u89AA");
console.log(index_1.SIX_REL[0].getSymbol());
var result = index_1.SIX_RELATIVE.antiVersal(index_1.SIX_REL[0], 1);
console.log(result.getSymbol());
console.log(index_1.SIX_REL[0].getSymbol());
var result1 = index_1.SIX_RELATIVE.transversal(index_1.SIX_REL[0], 1);
console.log(result1.getSymbol());
