"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var EARTH_SYMBOL;
(function (EARTH_SYMBOL) {
    EARTH_SYMBOL[EARTH_SYMBOL["\u5B50"] = 0] = "\u5B50";
    EARTH_SYMBOL[EARTH_SYMBOL["\u5BC5"] = 1] = "\u5BC5";
    EARTH_SYMBOL[EARTH_SYMBOL["\u8FB0"] = 2] = "\u8FB0";
    EARTH_SYMBOL[EARTH_SYMBOL["\u5348"] = 3] = "\u5348";
    EARTH_SYMBOL[EARTH_SYMBOL["\u7533"] = 4] = "\u7533";
    EARTH_SYMBOL[EARTH_SYMBOL["\u620C"] = 5] = "\u620C";
    EARTH_SYMBOL[EARTH_SYMBOL["\u672A"] = 6] = "\u672A";
    EARTH_SYMBOL[EARTH_SYMBOL["\u5DF3"] = 7] = "\u5DF3";
    EARTH_SYMBOL[EARTH_SYMBOL["\u536F"] = 8] = "\u536F";
    EARTH_SYMBOL[EARTH_SYMBOL["\u4E11"] = 9] = "\u4E11";
    EARTH_SYMBOL[EARTH_SYMBOL["\u4EA5"] = 10] = "\u4EA5";
    EARTH_SYMBOL[EARTH_SYMBOL["\u9149"] = 11] = "\u9149";
})(EARTH_SYMBOL || (EARTH_SYMBOL = {}));
exports.EARTH_SYMBOL = EARTH_SYMBOL;
;
var SIX_RELATIVE_SYMBOL;
(function (SIX_RELATIVE_SYMBOL) {
    SIX_RELATIVE_SYMBOL[SIX_RELATIVE_SYMBOL["\u5144"] = 0] = "\u5144";
    SIX_RELATIVE_SYMBOL[SIX_RELATIVE_SYMBOL["\u7236"] = 1] = "\u7236";
    SIX_RELATIVE_SYMBOL[SIX_RELATIVE_SYMBOL["\u5B98"] = 2] = "\u5B98";
    SIX_RELATIVE_SYMBOL[SIX_RELATIVE_SYMBOL["\u624D"] = 3] = "\u624D";
    SIX_RELATIVE_SYMBOL[SIX_RELATIVE_SYMBOL["\u5B50"] = 4] = "\u5B50";
})(SIX_RELATIVE_SYMBOL || (SIX_RELATIVE_SYMBOL = {}));
exports.SIX_RELATIVE_SYMBOL = SIX_RELATIVE_SYMBOL;
;
